common:
  img_topic: "/camera/image_color"
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  semantic_risk_visual_topic: "/semantic_risk_visual"
  semantic_risk_lidar_topic: "/semantic_risk_lidar"
  semantic_risk_visual_map_topic: "/semantic_risk_visual_map"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [0.04165, 0.02326, -0.0284]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  Rcl: [-0.00113207, -0.9999999, 0.000504622,
        -0.0158688, -0.000486594, -0.999874,
        0.999873, -0.00113994, -0.0158682]
  Pcl: [-0.0233214796543, 0.02772416790356, 0.0420688523256]

time_offset:
  imu_time_offset: 0.0
  img_time_offset: 0.0
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 1
  filter_size_surf: 0.1
  lidar_type: 1
  scan_line: 6
  blind: 0.8

vio:
  max_iterations: 5
  outlier_threshold: 1000
  img_point_cov: 100
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.5
  gyr_cov: 0.3
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0025
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: true
  pub_effect_point_en: false
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0
  gs_output_en: true
  gs_plane_output_en: true
  gs_plane_point_skip: 1
  gs_plane_max_samples: 5000
  gs_plane_min_confidence: 0.2
  gs_depth_history: 5
  gs_point_skip: 10
  gs_publish_delay_frames: 2
  gs_max_depth: 20.0
  gs_rectify_image: true
  gs_image_width: 640
  gs_image_height: 512
  gs_source_fx: 431.71205
  gs_source_fy: 431.70855
  gs_source_cx: 320.34040
  gs_source_cy: 259.16960
  gs_source_distortion: [-0.1080, 0.1050, -0.00012872, 0.000057923, -0.0222]
  gs_fx: 431.71205
  gs_fy: 431.70855
  gs_cx: 320.34040
  gs_cy: 259.16960

evo:
  seq_name: "r3live_hku"
  pose_output_en: true

pcd_save:
  pcd_save_en: false
  type: 0
  colmap_output_en: false
  filter_size_pcd: 0.15
  interval: -1

image_save:
  img_save_en: false
  interval: 1
